In [1]:
import pandas as pd
import numpy as np

In [2]:
datasetPath = "../datasets/"
domicilioPath = "domicilio.sas7bdat"
moradorPath = "morador.sas7bdat"
consumoPath = "consumo.sas7bdat"
dietaPath = "caract_dieta.sas7bdat"

In [3]:

dfDomicilio = pd.read_sas(datasetPath+domicilioPath)
dfMorador = pd.read_sas(datasetPath+moradorPath)
dfConsumo = pd.read_sas(datasetPath+consumoPath)
dfDieta = pd.read_sas(datasetPath+dietaPath)

## Domicílio

In [4]:
# Tamanho
print(dfDomicilio.shape)

(57920, 39)


In [5]:
# Atributos
print(list(dfDomicilio.keys()))

['UF', 'ESTRATO_POF', 'TIPO_SITUACAO_REG', 'COD_UPA', 'NUM_DOM', 'V0201', 'V0202', 'V0203', 'V0204', 'V0205', 'V0206', 'V0207', 'V0208', 'V0209', 'V02101', 'V02102', 'V02103', 'V02104', 'V02105', 'V02111', 'V02112', 'V02113', 'V0212', 'V0213', 'V02141', 'V02142', 'V0215', 'V02161', 'V02162', 'V02163', 'V02164', 'V0217', 'V0219', 'V0220', 'V0221', 'PESO', 'PESO_FINAL', 'V6199', 'iddomic']


In [6]:
dfDomicilio.head()

UF  ESTRATO_POF  TIPO_SITUACAO_REG      COD_UPA  NUM_DOM  V0201  V0202  \
0  11.0       1103.0                1.0  110005400.0      1.0    1.0    1.0   
1  11.0       1103.0                1.0  110005400.0      2.0    1.0    1.0   
2  11.0       1103.0                1.0  110005400.0      4.0    1.0    4.0   
3  11.0       1103.0                1.0  110005400.0      5.0    1.0    4.0   
4  11.0       1103.0                1.0  110005400.0      6.0    1.0    1.0   

   V0203  V0204  V0205  ...  V02163  V02164  V0217  V0219  V0220  V0221  \
0    1.0    1.0   10.0  ...     1.0     2.0    1.0    NaN    1.0    1.0   
1    1.0    1.0    5.0  ...     1.0     2.0    3.0    1.0    1.0    1.0   
2    1.0    1.0    5.0  ...     2.0     2.0    1.0    NaN    1.0    1.0   
3    1.0    1.0    7.0  ...     2.0     2.0    1.0    NaN    2.0    1.0   
4    1.0    1.0    6.0  ...     2.0     2.0    1.0    NaN    1.0    1.0   

         PESO  PESO_FINAL  V6199       iddomic  
0  272.806669  372.984516    1.0  1.100054e+13  
1  272.806669  372.984516    1.0  1.100054e+13  
2  272.806669  372.984516    1.0  1.100054e+13  
3  272.806669  372.984516    1.0  1.100054e+13  
4  272.806669  372.984516    1.0  1.100054e+13  

[5 rows x 39 columns]

## Morador

In [7]:
# Tamanho
print(dfMorador.shape)

(178431, 68)


In [8]:
# Atributos
print(list(dfMorador.keys()))

['iddomic', '_TYPE_', '_FREQ_', 'esc_ref2', 'n_pessoa', 'UF', 'ESTRATO_POF', 'TIPO_SITUACAO_REG', 'COD_UPA', 'NUM_DOM', 'NUM_UC', 'COD_INFORMANTE', 'V0306', 'V0401', 'V04021', 'V04022', 'V04023', 'V0403', 'V0404', 'V0405', 'V0406', 'V0407', 'V0408', 'V0409', 'V0410', 'V0411', 'V0412', 'V0413', 'V0414', 'V0415', 'V0416', 'V041711', 'V041712', 'V041721', 'V041722', 'V041731', 'V041732', 'V041741', 'V041742', 'V0418', 'V0419', 'V0420', 'V0421', 'V0422', 'V0423', 'V0424', 'V0425', 'V0426', 'V0427', 'V0428', 'V0429', 'V0430', 'ANOS_ESTUDO', 'PESO', 'PESO_FINAL', 'RENDA_TOTAL', 'INSTRUCAO', 'COMPOSICAO', 'PC_RENDA_DISP', 'PC_RENDA_MONET', 'PC_RENDA_NAO_MONET', 'PC_DEDUCAO', 'id', 'esc', 'cond_familia', 'ref', 'raca', 'escola']


In [9]:
dfMorador['NUM_UC'].unique()

array([1., 2., 3.])

In [10]:
#V0306: Condição familiar com o principal da unidade de consumo
dfMorador[['COD_UPA', 'NUM_DOM', 'NUM_UC', 'COD_INFORMANTE', 'V0306']].head(50)

COD_UPA  NUM_DOM  NUM_UC  COD_INFORMANTE  V0306
0   110000016.0      2.0     1.0             1.0    1.0
1   110000016.0      2.0     1.0             2.0    2.0
2   110000016.0      2.0     1.0             3.0    6.0
3   110000016.0      3.0     1.0             1.0    1.0
4   110000016.0      3.0     1.0             2.0    2.0
5   110000016.0      3.0     1.0             3.0    5.0
6   110000016.0      3.0     1.0             4.0    4.0
7   110000016.0      4.0     1.0             1.0    1.0
8   110000016.0      4.0     1.0             2.0    5.0
9   110000016.0      5.0     1.0             1.0    1.0
10  110000016.0      5.0     1.0             2.0    2.0
11  110000016.0      5.0     1.0             3.0    5.0
12  110000016.0      5.0     1.0             4.0    5.0
13  110000016.0      5.0     1.0             5.0   10.0
14  110000016.0      7.0     1.0             1.0    1.0
15  110000016.0      7.0     1.0             2.0    2.0
16  110000016.0      7.0     1.0             3.0    4.0
17  110000016.0      7.0     1.0             4.0    6.0
18  110000016.0      7.0     1.0             5.0    6.0
19  110000016.0      8.0     1.0             1.0    1.0
20  110000016.0      8.0     1.0             2.0    2.0
21  110000016.0      8.0     1.0             3.0    4.0
22  110000016.0      8.0     1.0             4.0    6.0
23  110000016.0      9.0     1.0             1.0    1.0
24  110000016.0      9.0     1.0             2.0    2.0
25  110000016.0      9.0     1.0             3.0    4.0
26  110000016.0      9.0     1.0             4.0    4.0
27  110000016.0     10.0     1.0             1.0    1.0
28  110000016.0     10.0     1.0             2.0    2.0
29  110000016.0     10.0     1.0             3.0    4.0
30  110000016.0     10.0     1.0             4.0    4.0
31  110000016.0     12.0     1.0             1.0    1.0
32  110000016.0     12.0     1.0             2.0    2.0
33  110000016.0     12.0     1.0             3.0    6.0
34  110000016.0     12.0     1.0             4.0    5.0
35  110000016.0     13.0     1.0             1.0    1.0
36  110000584.0      2.0     1.0             1.0    1.0
37  110000584.0      2.0     1.0             2.0    5.0
38  110000584.0      2.0     1.0             3.0    5.0
39  110000584.0      2.0     1.0             4.0   10.0
40  110000584.0      3.0     1.0             1.0    1.0
41  110000584.0      3.0     1.0             2.0    2.0
42  110000584.0      3.0     1.0             3.0    4.0
43  110000584.0      3.0     1.0             4.0    4.0
44  110000584.0      3.0     1.0             5.0   10.0
45  110000584.0      6.0     1.0             1.0    1.0
46  110000584.0      6.0     1.0             2.0    2.0
47  110000584.0      6.0     1.0             3.0    7.0
48  110000584.0      6.0     1.0             4.0    4.0
49  110000584.0      6.0     1.0             5.0   10.0

## Característica da Dieta

In [11]:
## Tamanho
print(dfDieta.shape)

(46164, 89)


In [12]:
## Atributos
print(list(dfDieta.keys()))

['iddomic', '_TYPE_', '_FREQ_', 'esc_ref2', 'n_pessoa', 'UF', 'ESTRATO_POF', 'TIPO_SITUACAO_REG', 'COD_UPA', 'NUM_DOM', 'NUM_UC', 'COD_INFORMANTE', 'V0306', 'V0401', 'V04021', 'V04022', 'V04023', 'V0403', 'V0404', 'V0405', 'V0406', 'V0407', 'V0408', 'V0409', 'V0410', 'V0411', 'V0412', 'V0413', 'V0414', 'V0415', 'V0416', 'V041711', 'V041712', 'V041721', 'V041722', 'V041731', 'V041732', 'V041741', 'V041742', 'V0418', 'V0419', 'V0420', 'V0421', 'V0422', 'V0423', 'V0424', 'V0425', 'V0426', 'V0427', 'V0428', 'V0429', 'V0430', 'ANOS_ESTUDO', 'PESO', 'PESO_FINAL', 'RENDA_TOTAL', 'INSTRUCAO', 'COMPOSICAO', 'PC_RENDA_DISP', 'PC_RENDA_MONET', 'PC_RENDA_NAO_MONET', 'PC_DEDUCAO', 'id', 'esc', 'cond_familia', 'raca', 'V7101', 'V7102', 'V71031', 'V71032', 'V71033', 'V71034', 'V71035', 'V71036', 'V71037', 'V71038', 'V7104', 'V71051', 'V71052', 'V71053', 'V71054', 'V71055', 'V71056', 'V71A01', 'V71A02', 'V72C01', 'V72C02', 'imc', 'estnutri']


In [13]:
dfDieta['estnutri'].unique()

array([3., 2., 1., 4.])

In [14]:
dfDieta[['V72C01', 'V72C02', 'imc', 'estnutri']]

V72C01  V72C02        imc  estnutri
0        64.0   154.0  26.986001       3.0
1        53.0   144.0  25.559414       3.0
2        80.0   180.0  24.691358       2.0
3        76.0   168.0  26.927438       3.0
4        58.0   145.0  27.586207       3.0
...       ...     ...        ...       ...
46159    93.0   166.0        NaN       4.0
46160    86.0   163.0  32.368550       4.0
46161    64.0   163.0  24.088223       2.0
46162    49.0   157.0  19.879103       2.0
46163    62.0   169.0  21.707923       2.0

[46164 rows x 4 columns]

In [15]:
dfDieta.shape

(46164, 89)

In [16]:
dfDieta['V71051'].isna().sum()

39689

In [17]:
dfDieta['V71051'].isna().sum()

39689

## Consumo

In [18]:
## Tamanho
print(dfConsumo.shape)

(1175390, 69)


In [19]:
## Atributos
print( list(dfConsumo.keys()))

['UF', 'ESTRATO_POF', 'TIPO_SITUACAO_REG', 'COD_UPA', 'NUM_DOM', 'NUM_UC', 'COD_INFORMANTE', 'QUADRO', 'SEQ', 'V9005', 'V9007', 'V9001', 'V9015', 'V9016', 'V9017', 'V9018', 'V9019', 'V9020', 'V9021', 'V9022', 'V9023', 'V9024', 'V9025', 'V9026', 'V9027', 'V9028', 'V9029', 'V9030', 'COD_UNIDADE_MEDIDA_FINAL', 'COD_PREPARACAO_FINAL', 'GRAMATURA1', 'QTD', 'COD_TBCA', 'ENERGIA_KCAL', 'ENERGIA_KJ', 'PTN', 'CHOTOT', 'FIBRA', 'LIP', 'COLEST', 'AGSAT', 'AGMONO', 'AGPOLI', 'AGTRANS', 'CALCIO', 'FERRO', 'SODIO', 'MAGNESIO', 'FOSFORO', 'POTASSIO', 'COBRE', 'ZINCO', 'VITA_RAE', 'TIAMINA', 'RIBOFLAVINA', 'NIACINA', 'PIRIDOXAMINA', 'COBALAMINA', 'VITD', 'VITE', 'VITC', 'FOLATO', 'PESO', 'PESO_FINAL', 'RENDA_TOTAL', 'DIA_SEMANA', 'DIA_ATIPICO', 'id', 'iddomic']


In [20]:
dfConsumo[['COD_UPA', 'NUM_DOM', 'NUM_UC', 'COD_INFORMANTE', 'QUADRO', 'SEQ', 'V9015','DIA_SEMANA']].head(50)

COD_UPA  NUM_DOM  NUM_UC  COD_INFORMANTE  QUADRO   SEQ   V9015  \
0   110000016.0      2.0     1.0             1.0    72.0   1.0   b'8H'   
1   110000016.0      2.0     1.0             1.0    72.0   1.0   b'8H'   
2   110000016.0      2.0     1.0             1.0    72.0   2.0   b'8H'   
3   110000016.0      2.0     1.0             1.0    72.0   2.0   b'8H'   
4   110000016.0      2.0     1.0             1.0    72.0   3.0  b'12H'   
5   110000016.0      2.0     1.0             1.0    72.0   4.0  b'12H'   
6   110000016.0      2.0     1.0             1.0    72.0   5.0  b'12H'   
7   110000016.0      2.0     1.0             1.0    72.0   6.0  b'14H'   
8   110000016.0      2.0     1.0             1.0    72.0   7.0  b'20H'   
9   110000016.0      2.0     1.0             1.0    72.0   8.0  b'20H'   
10  110000016.0      2.0     1.0             1.0    72.0   9.0  b'20H'   
11  110000016.0      2.0     1.0             1.0    72.0  10.0  b'22H'   
12  110000016.0      2.0     1.0             1.0    73.0   1.0   b'8H'   
13  110000016.0      2.0     1.0             1.0    73.0   1.0   b'8H'   
14  110000016.0      2.0     1.0             1.0    73.0   2.0   b'8H'   
15  110000016.0      2.0     1.0             1.0    73.0   2.0   b'8H'   
16  110000016.0      2.0     1.0             1.0    73.0   3.0  b'12H'   
17  110000016.0      2.0     1.0             1.0    73.0   4.0  b'12H'   
18  110000016.0      2.0     1.0             1.0    73.0   5.0  b'12H'   
19  110000016.0      2.0     1.0             1.0    73.0   6.0  b'19H'   
20  110000016.0      2.0     1.0             1.0    73.0   6.0  b'19H'   
21  110000016.0      2.0     1.0             1.0    73.0   7.0  b'19H'   
22  110000016.0      2.0     1.0             1.0    73.0   7.0  b'19H'   
23  110000016.0      2.0     1.0             1.0    73.0   8.0  b'20H'   
24  110000016.0      2.0     1.0             1.0    73.0   9.0  b'14H'   
25  110000016.0      2.0     1.0             1.0    73.0   9.0  b'14H'   
26  110000016.0      2.0     1.0             2.0    72.0   1.0   b'8H'   
27  110000016.0      2.0     1.0             2.0    72.0   1.0   b'8H'   
28  110000016.0      2.0     1.0             2.0    72.0   2.0   b'7H'   
29  110000016.0      2.0     1.0             2.0    72.0   2.0   b'7H'   
30  110000016.0      2.0     1.0             2.0    72.0   3.0  b'12H'   
31  110000016.0      2.0     1.0             2.0    72.0   4.0  b'12H'   
32  110000016.0      2.0     1.0             2.0    72.0   5.0  b'12H'   
33  110000016.0      2.0     1.0             2.0    72.0   6.0  b'14H'   
34  110000016.0      2.0     1.0             2.0    72.0   7.0  b'20H'   
35  110000016.0      2.0     1.0             2.0    72.0   8.0  b'20H'   
36  110000016.0      2.0     1.0             2.0    72.0   9.0  b'20H'   
37  110000016.0      2.0     1.0             2.0    72.0  10.0  b'22H'   
38  110000016.0      2.0     1.0             2.0    73.0   1.0   b'8H'   
39  110000016.0      2.0     1.0             2.0    73.0   1.0   b'8H'   
40  110000016.0      2.0     1.0             2.0    73.0   2.0   b'8H'   
41  110000016.0      2.0     1.0             2.0    73.0   2.0   b'8H'   
42  110000016.0      2.0     1.0             2.0    73.0   3.0  b'12H'   
43  110000016.0      2.0     1.0             2.0    73.0   4.0  b'12H'   
44  110000016.0      2.0     1.0             2.0    73.0   5.0  b'12H'   
45  110000016.0      2.0     1.0             2.0    73.0   6.0  b'14H'   
46  110000016.0      2.0     1.0             2.0    73.0   6.0  b'14H'   
47  110000016.0      2.0     1.0             2.0    73.0   7.0  b'16H'   
48  110000016.0      2.0     1.0             2.0    73.0   7.0  b'16H'   
49  110000016.0      2.0     1.0             2.0    73.0   8.0  b'16H'   

         DIA_SEMANA  
0   b'Quarta-Feira'  
1   b'Quarta-Feira'  
2   b'Quarta-Feira'  
3   b'Quarta-Feira'  
4   b'Quarta-Feira'  
5   b'Quarta-Feira'  
6   b'Quarta-Feira'  
7   b'Quarta-Feira'  
8   b'Quarta-Feira'  
9   b'Quarta-

In [21]:
np.sum(dfConsumo.QUADRO==72)

644610

In [27]:
np.sum(dfConsumo.QUADRO==73)

530780

In [22]:
dfConsumo.nlargest(n=10, columns=['PTN'])['PTN']

198976     1010.9220
199009     1010.9220
32173       897.3195
992995      712.7760
140519      629.2440
313652      598.2130
1120268     598.2130
1089501     571.8400
925108      537.0000
669244      533.8800
Name: PTN, dtype: float64

In [23]:
dfConsumo['PTN'].mean()

5.850694898309581

In [24]:
dfConsumo['ENERGIA_KCAL'].mean()

126.79023852743335

In [25]:
dfConsumo['CHOTOT'].mean()

16.993195244616086

In [26]:
dfConsumo['QUADRO'].unique()

array([72., 73.])

In [29]:
for row in dfConsumo:
    print(row)

UF
ESTRATO_POF
TIPO_SITUACAO_REG
COD_UPA
NUM_DOM
NUM_UC
COD_INFORMANTE
QUADRO
SEQ
V9005
V9007
V9001
V9015
V9016
V9017
V9018
V9019
V9020
V9021
V9022
V9023
V9024
V9025
V9026
V9027
V9028
V9029
V9030
COD_UNIDADE_MEDIDA_FINAL
COD_PREPARACAO_FINAL
GRAMATURA1
QTD
COD_TBCA
ENERGIA_KCAL
ENERGIA_KJ
PTN
CHOTOT
FIBRA
LIP
COLEST
AGSAT
AGMONO
AGPOLI
AGTRANS
CALCIO
FERRO
SODIO
MAGNESIO
FOSFORO
POTASSIO
COBRE
ZINCO
VITA_RAE
TIAMINA
RIBOFLAVINA
NIACINA
PIRIDOXAMINA
COBALAMINA
VITD
VITE
VITC
FOLATO
PESO
PESO_FINAL
RENDA_TOTAL
DIA_SEMANA
DIA_ATIPICO
id
iddomic
